### ISSUE TITLE
iOS: Crash when trying to load a stream

### ISSUE THREAD

**Issue by ponkey364** [Glimesh/glimesh_app#16]
Tried to open a stream on the latest commit of the app on iOS, seems like iOS might think we're trying to use the microphone:

```
flutter: [INFO] JanusClient: Creating Session
flutter: [FINE] JanusClient: fine message
flutter: [INFO] JanusClient: Session Created
flutter: [INFO] JanusClient: using rest transport for creating plugin handle
flutter: [FINE] JanusClient: {janus: success, session_id: 94069246441168, transaction: e16ee2ab-eadb-462b-af33-3cc88ce3aa16, data: {id: 8277653896468042}}
flutter: [FINE] JanusClient: peer connection configuration
flutter: [FINE] JanusClient: {iceServers: [], sdpSemantics: plan-b}
[access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.
* thread #2, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
    frame #0: 0x00000001ca9e9154 libsystem_kernel.dylib`__abort_with_payload + 8
libsystem_kernel.dylib`__abort_with_payload:
->  0x1ca9e9154 <+8>:  b.lo   0x1ca9e9170               ; <+36>
    0x1ca9e9158 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1ca9e915c <+16>: mov    x29, sp
    0x1ca9e9160 <+20>: bl     0x1ca9c71fc               ; cerror_nocancel
```

I botched the key into the info.plist and then it worked and I get video without a crash but, after what you'd said on Discord the other day about sound coming from the earpiece speaker, and that my phone suddenly decided to make noise (and made me jump, lol) I think somewhere (maybe in the janus library?) making devices think we're a VOIP app?

**Comment by ponkey364** [comment]
did a tad of digging on this today, I'm way out of my depth, but there's been some issues opened in flutter-webrtc wrt telling the device that the app is doing media and not VOIP, but they've been closed with wontfix and one led me to a [code review on libwebrtc](https://codereview.webrtc.org/2411263003/#ps1) which implemented the change needed for this that was reverted because of a race condition.

unsure as where to go from here :/

**Comment by ponkey364** [comment]
coming back to this with an update because today is full of surprises: upgrading flutter_webrtc seemingly stopped it asking for permission, so I guess this is sorted?

**Comment by clone1018** [comment]
Are you still experiencing this issue @ponkey364 ?

**Comment by ponkey364** [comment]
No, I think those upgrades we did fixed it.
