### ISSUE TITLE
Keep video open and playing while the user is watching

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh_app#23]
We should use something like https://pub.dev/packages/flutter_incall to prevent the phone from turning off the screen while users are watching a stream, unless the user specifically hits the power button.

**Comment by ponkey364** [comment]
I'm having a look at this, but from a bit of testing before doing anything, it seems that, at least on iOS, the screen doesn't turn off while watching streams (at least, not during the 15 minutes+ that I ran for), is this just an Android thing?
